### ISSUE TITLE
Consertar Login CEI-B3

### ISSUE THREAD

**Issue by renanleonellocastro** [renanleonellocastro/darf_generator#30]
## Objetivo
O sistema _**CEI-B3**_  adicionou um campo novo no Login, o campo de _**reCAPTCHA**_ . É necessário consertar o sistema de conexão com o _**CEI-B3**_  para lidar com a resolução do _**reCAPTCHA**_  se possível.

### Procedimento

- [ ] Estudar sobre formas de lidar com o campo _**reCAPTCHA**_  adicionado no login do _**CEI-B3**_ .
- [x] Implementar uma possível solução.
- [x] Realizar testes.
- [x] Commitar as modificações implementadas.

### Conclusão
Após concluídas as tarefas, marcá-las como concluídas no  _**Issue**_ e commitar as mudanças. Realizar um _**pull request**_ para o _**master**_ adicionando o número da _**Issue**_ no comentário.

**Comment by franciswagner** [comment]
Só usar essa url, @renanleonellocastro: https://ceiapp.b3.com.br/CEI_Responsivo/login.aspx

**Comment by renanleonellocastro** [comment]
Muito obrigado @franciswagner! Vou testar sua solução.
